env:
  browser: true
  es2021: true
extends: google
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-multiple-empty-lines: ["error", { "max": 1, "maxEOF": 0, "maxBOF": 0 }],
  no-unused-vars: "warn",
  camelcase: "warn"
}
